import React, { useState } from 'react'
import styles from "../styles/Home.module.css"
import Head from "next/head";
import LoginComponent from '../Componets/LoginComponent';
import SignInComponent from '../Componets/SignInComponent';

const Auth = () => {



    const [authMethod, setAuthMethod] = useState("Login");

  const changeAuthMethodState = (method) => {
    setAuthMethod(method);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Secure Social Media Content</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Secure Social Media Content</h1>

        <div className="authMethodContainer">
          <div
            className={`loginMethod ${authMethod === "Login"?"activeAuthState":""}`}
            onClick={() => changeAuthMethodState("Login")}
          >
            Login
          </div>
          <div
            className={`signInMethod ${authMethod === "Create Account"?"activeAuthState":""}`}
            onClick={() => changeAuthMethodState("Create Account")}
          >
            Create Account
          </div>
        </div>
        <div className="authContainer">
          {authMethod === "Login"?(
            <LoginComponent />
          ):(
            <SignInComponent/>
          )}
        </div>
      </main>
    </div>
  )
}

export default Auth