import Head from "next/head";
import { useState } from "react";
import LoginComponent from "../Componets/LoginComponent";
import SignInComponent from "../Componets/SignInComponent";
import Link from "next/link"
import Typed from 'typed.js';

import styles from "../styles/Home.module.css";

export default function Home() {
  const [authMethod, setAuthMethod] = useState("Login");

  const changeAuthMethodState = (method) => {
    setAuthMethod(method);
  };

  return (
    <div className="landingPageContainer">
      <Head>
        <title>Secure Social Media Content</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Secure Social Media Content</h1>
      <Link className="toAuthPage" href="/auth">
        Click Here
      </Link>
      
    </div>
  );
}
